Update phone
thomasfritzboger/ca1_ver2 pull request #12
Opened 2022-10-24 04:15 UTC by thomasfritzboger

Der kan nok refaktoreres noget, kan vi måske se på onsdag
Rest test består nogen gange, tror det er en cache ting, men hvis man kører test nok gange 3-4 ender de med at bestå??
NotPhoneOwnerException kunne måske hedde IlligalOwnershipException isf?

2022-10-24 07:14 UTC, Ionsight requested changes
I've made a very detailed review.

Some attention to detail can be improved. But overall it looks very good!
I haven't looked into the problems that you have reported on tests failing sometimes. We can look into that together Wednesday.

For future pull requests, I would recommend that you refer back to my comments on this pull request before requesting. You might catch something you've forgotten.

2022-10-24 07:14 UTC, Ionsight commented on src/test/java/facades/PersonFacadeTest.java
> +        assertDatabaseHasEntity(phonePersonA,phonePersonA.getId());
It makes a lot of sense checking if we have overwritten personA's phone! Very nice thinking, I hadn't thought of that. But make sure that you are actually testing that, since you haven't refreshed `phonePersonA`

2022-10-24 07:14 UTC, Ionsight commented on src/test/java/facades/PersonFacadeTest.java
> +    void removePhoneSomeoneElseOwnTest() {
Again, this should be the responsibility of the resource, not the facade

2022-10-24 07:14 UTC, Ionsight commented on src/test/java/rest/PersonResourceTest.java
> +    void putAddPhoneTest() {
Makes sense to test multiple phones. But instead of calling the endpoint multiple times, you could add the first phone when you arrange the test. And if you also want to to test when they have no phones and then add one, you can do that in another test. Otherwise, the test becomes too long and hard to read as you are setting up multiple arranges/prerequisites

2022-10-24 07:14 UTC, Ionsight commented on src/test/java/rest/PersonResourceTest.java
> +
At least three more tests:

add phone when person does not exist
remove phone when person does not exist
remove phone when phone does not exist

2022-11-06 15:01 UTC, Wolfgang1235 approved these changes

2022-11-06 15:02 UTC, merged